#!/usr/bin/env bash
# Write /etc/ai-dev-worker/deploy.env for the vps-dev closure scripts.
#
# Run as root ON THE VPS. Nothing is ever printed: the closure bearer is
# derived from HUB_TOKEN in place and written straight to the target file, so
# no secret passes through a terminal, a chat transcript or an agent context.
#
#   AI_HUB_TOKEN        = HMAC-SHA256(HUB_TOKEN, 'closure-v1\0<clientId>')
#                         Read-only, GET-only credential; scope is enforced by
#                         server/src/middleware/closureAuth.ts. NOT HUB_TOKEN —
#                         it cannot log in, mint a session, or write anything.
#   AI_HUB_DEPLOY_TOKEN = the existing DEPLOY_TOKEN, unchanged.
#
# Re-run after every HUB_TOKEN rotation: derived tokens die with their key.
set -euo pipefail

HUB_ENV=${HUB_ENV:-/opt/ai-hub/.env}
TARGET=${TARGET:-/etc/ai-dev-worker/deploy.env}
CLIENT_ID=${CLIENT_ID:-vps-dev}
OWNER=${OWNER:-root:ai-dev}

[ -r "$HUB_ENV" ] || { echo "cannot read $HUB_ENV (run as root on the VPS)" >&2; exit 1; }

# shellcheck disable=SC2046
hub=$(sed -n 's/^HUB_TOKEN=//p' "$HUB_ENV" | head -n1)
deploy=$(sed -n 's/^DEPLOY_TOKEN=//p' "$HUB_ENV" | head -n1)
[ -n "$hub" ] || { echo "HUB_TOKEN not found in $HUB_ENV" >&2; exit 1; }
[ -n "$deploy" ] || { echo "DEPLOY_TOKEN not found in $HUB_ENV; enable the deploy endpoint first" >&2; exit 1; }

closure=$(HUB_TOKEN="$hub" CLIENT_ID="$CLIENT_ID" node -e '
const c = require("crypto");
process.stdout.write(
  c.createHmac("sha256", process.env.HUB_TOKEN)
    .update(`closure-v1\0${process.env.CLIENT_ID}`)
    .digest("base64url"),
);
')

mkdir -p "$(dirname "$TARGET")"
[ -e "$TARGET" ] && cp -a "$TARGET" "$TARGET.bak-$(date -u +%Y%m%dT%H%M%SZ)"
umask 027
tmp=$(mktemp "$(dirname "$TARGET")/.deploy.env.XXXXXX")
trap 'rm -f "$tmp"' EXIT
{
  echo "# generated by deploy/install-closure-env.sh; re-run after a HUB_TOKEN rotation"
  echo "AI_HUB_TOKEN=$closure"
  echo "AI_HUB_DEPLOY_TOKEN=$deploy"
} > "$tmp"
chown "$OWNER" "$tmp"
chmod 640 "$tmp"
mv "$tmp" "$TARGET"
trap - EXIT

# Only metadata is echoed, never a value.
ls -l "$TARGET"
echo "WROTE $TARGET (client=$CLIENT_ID, keys=AI_HUB_TOKEN,AI_HUB_DEPLOY_TOKEN)"
